#!/bin/bash

set -e

success_icon="\033[32m ✔\033[0m"
namespace=sls
image_name=web-record-base

# 更新升级应用后需要修改 tag_name 与 package.json 中版本一致
tag_name=latest

# 注入配置参数
#source ./.env

# 镜像构件函数
buildImage() {
  # 镜像服务域名
  image_url="web-record-base"

  # 镜像名称
  target_name="$image_url:$tag_name"

  # 构建
  docker build -f Dockerfile -t $target_name .
  echo -e "$success_icon 构件镜像"
}

# 构建镜像
buildImage

exit 0;
